### ISSUE TITLE
TODO: fixes/improvements

### ISSUE THREAD

**Issue by n3r0t** [n3r0t/cryptonero#1]
- [x] Remove `coin` var and improve returns https://github.com/n3r0t/cryptonero/blob/aba4ebdec590f929b7da6e2c10d8676bb0209e85/bot/crypto.py#L52

- [x] Remove EUR currency and clean the code https://github.com/n3r0t/cryptonero/blob/aba4ebdec590f929b7da6e2c10d8676bb0209e85/bot/crypto.py#L185

- [x] change if/else block for something better https://github.com/n3r0t/cryptonero/blob/aba4ebdec590f929b7da6e2c10d8676bb0209e85/bot/crypto.py#L360

- [ ] move to fun module https://github.com/n3r0t/cryptonero/blob/aba4ebdec590f929b7da6e2c10d8676bb0209e85/bot/crypto.py#L425

**Comment by n3r0t** [comment]
can't do fourth task, see 7b06a09e861b90e2820ef3d0ae952db9b8193874 comment
